### ISSUE TITLE
divider's visual bug

### ISSUE THREAD

**Issue by serge-ivamov** [stevengharris/SplitView#19]
``` swift
// …
let lh = LayoutHolder(.vertical)
// …
Split(primary: { Color.red }, secondary: { TabView { Color.green } })
    .layout(lh)
Button("bug") { withAnimation { lh.toggle() } }
Button("ok") { lh.toggle() }

// …
```
<img width="331" alt="Screenshot 2023-09-21 at 22 17 27" src="https://github.com/stevengharris/SplitView/assets/6604469/a3ac57f5-033d-49d4-8cc1-8c8dada5a360">

**Comment by serge-ivamov** [comment]
Tnx, Steven!

I am on Ventura 13.6 and the bug is still here, even with .tabItem().
Let's hope for Sonoma :)

**Comment by stevengharris** [comment]
It's very odd! I don't have a Ventura machine easily accessible, but I tried it on my old MacBook running Big Sur, and it also shows no issue.

The only time I have seen something looking like this has been when I messed something up in a custom splitter. The default Splitter gets its layout from the Environment, established in Split, so it *should* not be possible for it to get out-of-sync with the Split view like this shows. It looks visually like that is what happened here - that Splitter's value for `layout` is different than the value Split has.

Just to be sure we are testing the exact same thing in the same way, you could paste your code into the DemoApp so it replaces the `.simpleDefaults` case as follows:

```
case .simpleDefaults:
    let lh = LayoutHolder(.vertical)
    Split(primary: { Color.red }, secondary: { TabView { Color.green } })
        .layout(lh)
    Button("bug") { withAnimation { lh.toggle() } }
    Button("ok") { lh.toggle() }
```

If running the demo with this pasted-in shows the same problem for you, then I'm willing to blame it on a weird Ventura SwiftUI bug (that I'm not working around 😜).

**Comment by serge-ivamov** [comment]
<img width="252" alt="start" src="https://github.com/stevengharris/SplitView/assets/6604469/615900bf-8b8b-4aee-bfc1-9b5eb0ce8d8d">

at start


<img width="251" alt="1click" src="https://github.com/stevengharris/SplitView/assets/6604469/82ee21db-d867-41bf-b87a-168eaef90637">

first click

<img width="254" alt="2click" src="https://github.com/stevengharris/SplitView/assets/6604469/810aebaf-b3d4-4838-9271-2819b319af75">

second click

___

<img width="276" alt="1click+resize" src="https://github.com/stevengharris/SplitView/assets/6604469/89933f91-61b4-4c58-81f2-b9f55b8d5f72">

first click + a lil resize of window - it's autofixed.

**Comment by stevengharris** [comment]
Can you try it using DemoSplitter? It will look ugly, but if the layouts match between DemoSplitter and Split, then it will tell us if I might be able to fix it by using ObservedObject instead of Environment. Like this:

```
case .simpleDefaults:
    let lh = LayoutHolder(.vertical)
    Split(primary: { Color.red }, secondary: { TabView { Color.green } })
        .splitter { DemoSplitter(layout: lh, hide: SideHolder()) }
        .layout(lh)
    Button("bug") { withAnimation { lh.toggle() } }
    Button("ok") { lh.toggle() }
```

**Comment by serge-ivamov** [comment]
<img width="266" alt="Screenshot 2023-09-22 at 22 38 37" src="https://github.com/stevengharris/SplitView/assets/6604469/c6e82af3-4aa9-42c2-91b6-0199aaa23a0d">

at start

<img width="266" alt="Screenshot 2023-09-22 at 22 39 31" src="https://github.com/stevengharris/SplitView/assets/6604469/e52f6ea9-7017-4ef3-b913-75978b6d6b02">

1st click

<img width="294" alt="Screenshot 2023-09-22 at 22 42 54" src="https://github.com/stevengharris/SplitView/assets/6604469/89c9ed3a-2348-4948-820c-a9b8abeca719">

2nd click




so it works like w/o custom .splitter
BUT!!! with a 50% chance everything works correctly!
in 10 apps run – 5/5 bugged and ok.

**Comment by stevengharris** [comment]
I didn't realize it would be so confusing. The DemoSplitter is clear, so the triangle direction in the button is indicating the layout for the DemoSplitter. It's showing the same behavior as the Splitter, which is:

1. At start: DemoSplitter layout = .vertical, Split layout = .vertical
2. 1st click: DemoSplitter layout = .horizontal, Split layout = .vertical
3. 2nd click: DemoSplitter layout = .vertical, Split layout = .horizontal

I was thinking the Splitter was in the wrong orientation, but it's the Split view that's layed out wrong.

I would debug this myself if I could reproduce it. I don't know how much time you want to spend on it in this way. If you're up for more, here are some more things to try:

1. Hold the LayoutHolder in a @StateObject. So in DemoApp, it would look like:

```
struct DemoApp: View {
    @State private var demoID: DemoID = .simpleDefaults
    @StateObject private var lh = LayoutHolder(.vertical)
    
    var body: some View {
        let demo = demos[demoID]!
        VStack {
            DemoToolbar(demoID: $demoID)
            switch demoID {
            case .simpleDefaults:
                Split(primary: { Color.red }, secondary: { TabView { Color.green } })
                    .layout(lh)
                Button("bug") { withAnimation { lh.toggle() } }
...
```

2. Use a VStack instead of the TabView to see if it has the same problems:

```
struct DemoApp: View {
    @State private var demoID: DemoID = .simpleDefaults
    @StateObject private var lh = LayoutHolder(.vertical)
    
    var body: some View {
        let demo = demos[demoID]!
        VStack {
            DemoToolbar(demoID: $demoID)
            switch demoID {
            case .simpleDefaults:
                Split(primary: { Color.red }, secondary: {
                    VStack {
                        Button(lh.isHorizontal ? "Horizontal": "Vertical") {}
                        Color.green
                    }
                })
                .layout(lh)
                Button("bug") { withAnimation { lh.toggle() } }
...
```

**Comment by serge-ivamov** [comment]
1. still bugged

2.
<img width="294" alt="Screenshot 2023-09-23 at 10 22 03" src="https://github.com/stevengharris/SplitView/assets/6604469/5d838628-0756-4ae0-9075-28cfd1655fca">

no problems with VStack + Button.

3. VStack + TabView = bugged

P.S. btw, IMO, using an @EnvironmentObject is incorrect anyway, since it only stores them of one type, which will create problems if the splitter is used in further views.

**Comment by stevengharris** [comment]
Agreed on Environment. Looking at this problem, I thought: why did I do that!? I think it was something I did when I was sorting out some other problem and never reverted 🤷‍♂️. Thanks for spending so much time debugging. Let's see if it changes with Sonoma.

**Comment by serge-ivamov** [comment]
No bugs on Sonoma :)

**Comment by stevengharris** [comment]
Great!!! Thanks again for spending so much time looking into it.
