### ISSUE TITLE
Option to offset views instead of changing frame size

### ISSUE THREAD

**Issue by dch09** [stevengharris/SplitView#22]
My use case requires me to leave initial P View frame as it is, without resizing onDrag (it's a MapView, resizing it is slow and animates poorly on device). 
I adjusted your code to fit my requirements, by calculating the difference between container height and S View offset, and offsetting the P View. 

Is it something you'd like to have in this library? I could refactor this and create pull request. I believe some use cases could require a boolean flag for this option.

**Comment by stevengharris** [comment]
Indeed, this does sound like a good option for people. It was a little hard to find what was actually done amidst all the formatting changes in https://github.com/stevengharris/SplitView/pull/23 😜.

FWIW, I made one change to your PR before I did anything, in Split.swift, line 98, adding `.height: pHeight`:

```
.frame(width: pWidth, height: pHeight)
```

If I run the "Sidebars" SplitDemo with the option enabled:

```
Split(
    isResizing: false,
    primary: {
        List(leftItems, id: \.self) { item in
            Text(item)
                .lineLimit(1)
                .truncationMode(.tail)
        }
        .listStyle(.plain)
        .padding([.top], 8)
    },
    secondary: {
        Split(
            isResizing: false,
            primary: {
                VStack {
                    Text(middleText)
                        .frame(maxWidth: .infinity, alignment: .leading)
                    Spacer()
                }
                .padding(8)
            },
            secondary: {
                VStack {
                    Text(rightText)
                        .frame(maxWidth: .infinity, alignment: .leading)
                    Spacer()
                }
                .padding(8)
            }
        )
        .splitter { Splitter.line() }
        .constraints(minPFraction: 0.3, minSFraction: 0.2, priority: .secondary, dragToHideS: true)
        .layout(demo.holders[0].layout)
        .fraction(0.75)
        .hide(demo.holders[0].hide)
    }
)
```

the changes cause the primary sides to not show properly:

<img width="1136" alt="Screenshot 2023-09-30 at 8 59 38 AM" src="https://github.com/stevengharris/SplitView/assets/1020361/58297c8f-669f-412c-bd05-8390440efad8">

<img width="1136" alt="Screenshot 2023-09-30 at 8 59 58 AM" src="https://github.com/stevengharris/SplitView/assets/1020361/5211d838-29d7-4c74-b832-96d717a57817">

I don't really have a good way to test things, frankly, since it's all visual, so I use the DemoApp. The Sidebars demo is sometimes less forgiving than the ones using Colors, but the "Nested adjustable" also has the same problem.

<img width="1136" alt="Screenshot 2023-09-30 at 9 09 24 AM" src="https://github.com/stevengharris/SplitView/assets/1020361/7e97600a-cd6b-4de1-b412-83dbb4c2f3a6">

**Comment by dch09** [comment]
Hmm, I'll verify my changes again using provided demo app, before pushing new commits.
I did however change the way this setting is applied — now it's done using `.disableResizing()` modifier on the view itself.

**Comment by dch09** [comment]
> FWIW, I made one change to your PR before I did anything, in Split.swift, line 98, adding `.height: pHeight`:
> 
> ```
> .frame(width: pWidth, height: pHeight)
> ```

I skipped the height parameter intentionally. I'm using VSplit in my app and I needed the top View to keep its original height no matter what. That's why `isResizing` flag is used here, with the `.offset` modifier to act like in its original behaviour. 

I believe in HSplit, analogically the width should be omitted.

**Comment by dch09** [comment]
After some testing with DemoApp, I came to conclusion that this behaviour is kinda expected. 

If we disable resizing by setting `isResizing` flag to false, the view **won't** be resized to fit it's parent container. 
That was the goal for me, because I wanted to have a Map in split view. Resizing it while dragging was causing poor performance.

`.disableResizing(true)` therefore works as expected, it just disables the width adjusting in horizontal mode, height in vertical. 

However I do see the issue with this modifier, as it produces results that may be not entirely obvious and seem like a bug.

**Comment by stevengharris** [comment]
I'm not going to be able to merge a PR that causes such unexpected behavior when applied to something as simple as a space-filling Color.

The MapView seems to scale and resize perfectly fine for me:

```
struct DemoApp: View {
    @State private var demoID: DemoID = .simpleDefaults
    @State private var pRegion = MKCoordinateRegion(center: CLLocationCoordinate2D(latitude: 51.507222, longitude: -0.1275), span: MKCoordinateSpan(latitudeDelta: 0.5, longitudeDelta: 0.5))
    @State private var sRegion = MKCoordinateRegion(center: CLLocationCoordinate2D(latitude: 37.779379, longitude: -122.418433), span: MKCoordinateSpan(latitudeDelta: 0.5, longitudeDelta: 0.5))
    
    var body: some View {
        let demo = demos[demoID]!
        VStack {
            DemoToolbar(demoID: $demoID)
            switch demoID {
            case .simpleDefaults:
                HSplit(
                    left: { Map(coordinateRegion: $pRegion) },
                    right: { Map(coordinateRegion: $sRegion) }
                )
...
```

<img width="1136" alt="Screenshot 2023-09-30 at 8 59 38 AM" src="https://github.com/stevengharris/SplitView/assets/1020361/930d7b55-0345-490d-b1b5-824055dfb658">

If you have an expensive overlay that needs to be recalculates as sizing changes, then perhaps an alternative approach would be to use `onDrag` to disable it when dragging starts and then recalculate it when dragging ends (or position a button overlay to optionally recalculate it like the Yelp app does). If needed, you could do an `onDragEnd` view modifier that is invoked like `onDrag`, but in the `.onEnded` closure of `Split.drag(in:)`:

```
.onEnded { gesture in
    previousPosition = nil
    styling.previewHide = false     // We are never previewing the hidden state when drag ends
    hide.side = sideToHide()
    // The fullFraction is used to determine the sideToHide, so we need to reset when done dragging,
    // but *after* setting the hide.side.
    fullFraction = constrainedFraction
    fraction.value = constrainedFraction
    onDragEnd?()
}
```
