### ISSUE TITLE
Breakpoints & animations

### ISSUE THREAD

**Issue by dch09** [stevengharris/SplitView#24]
I'm planning on extending VSplit capabilities by breakpoints in my fork, which will result in something like PresentationDetents in sheets, or SwipeActions in List. 

If there's any need for that in the original repo I'd be glad to create pull request for that once it's done. 
Please share some API style guidelines if there are any requirements.

**Comment by stevengharris** [comment]
As I said in https://github.com/stevengharris/SplitView/issues/22, my preference in general is to enable optional new features into an existing modifier at the end of the existing options. I'm not sure how what you would do would work conceptually with the existing modifiers, so maybe a new modifier would be preferable. In general, I've tried to make sure that new capabilities work in Split, HSplit, and VSplit and then test manually using all the demos in DemoApp (or perhaps add a new one) on Mac Catalyst, MacOS, and an iOS device.
