### ISSUE TITLE
Text and/or systemImage in splitter only possible in customsplitviews?

### ISSUE THREAD

**Issue by eduo** [stevengharris/SplitView#38]
Maybe a simple question but for the default splitter the only styling available is color and width? I see the custom splitter having symbols as well but they don't seem to be available in the default one.

**Comment by eduo** [comment]
I'll answer to myself: Default splitters are the bar and invisible. Splitters with different designs can be made and submitted for inclusion, but customizing the default splitters is not currently built-in

**Comment by stevengharris** [comment]
Yes, you should be able to use pretty much any view you create as a splitter by conforming to SplitDivider and observing layout, hide, and styling as needed.
