### ISSUE TITLE
Issue When Dragging a Splitter Outside the Parent Window on MacOS

### ISSUE THREAD

**Issue by dleuck** [stevengharris/SplitView#5]
If you drag outside the window on MacOS the position of the cursor relative to the splitter is changed by the distance travelled outside the window. When you reenter the window your pointer is no longer over the splitter.

BTW - This is a great library. It is exactly what I needed.

**Comment by stevengharris** [comment]
Thanks very much for letting me know. I will check it out.

**Comment by stevengharris** [comment]
This should be fixed in https://github.com/stevengharris/SplitView/commit/b43b07b06aefc5a0daf574938e3b55a47390bcc4 and tagged as 3.1.3 so you can just update the package.

**Comment by dleuck** [comment]
Thank you! I was working on a PR, but you beat me to it. :-)

**Comment by dleuck** [comment]
Fixed cursor location issue after exiting and re-entering window.
