### ISSUE TITLE
Instantiating from a simpler format?

### ISSUE THREAD

**Issue by cannyboy** [stevengharris/SplitView#6]
Is there a way to instantiate a layout from a simpler kind of format, which just shows the position and size of each View.

(this ignores colours, which would have to be passed via JSON somehow)

So a four-view layout (2 by 2) could be expressed like so,
```
// json, numbers are percentages
{
    "views": [
        {
            "width": 50,
            "height": 50,
            "x": 0,
            "y": 0
        },
        {
            "width": 50,
            "height": 50,
            "x": 50,
            "y": 0
        },
        {
            "width": 50,
            "height": 50,
            "x": 0,
            "y": 50
        },
        {
            "width": 50,
            "height": 50,
            "x": 50,
            "y": 50
        }
    ]
}

// swift
struct SView: Identifiable, Codable, Hashable {
    var id = UUID()
    let width: CGFloat
    let height: CGFloat
    let x: CGFloat
    let y: CGFloat

    enum CodingKeys: String, CodingKey {
        case width, height, x, y
    }
}
```

**Comment by stevengharris** [comment]
I don't think so, at least in the 4x4 case you are showing. The notion of splitting two views is at the heart of what SplitView is doing, so the layout is always between 2 views. It would need to be done by splitting two views at a time to produce a 4x4:

```
HSplit(
    left: { VSplit(top: { Color.green }, bottom: { Color.blue} ) },
    right: { VSplit(top: { Color.red }, bottom: { Color.yellow }) }
)
```

or 

```
VSplit(
    top: { HSplit(left: { Color.green }, right: { Color.red} ) },
    bottom: { HSplit(left: { Color.blue }, right: { Color.yellow }) }
)
```

The top 4x4 has a single splitter that slides horizontally, and the bottom has one that slides vertically. I'm guessing you want each side within the 4x4 to be independently slidable, though, not this.

<img width="1053" alt="Screenshot 2023-05-18 at 9 26 48 AM" src="https://github.com/stevengharris/SplitView/assets/1020361/9b2d7f12-8c43-4265-90de-e4cda9ccd46b">

If one of these two layouts is what you're after, then it would be pretty simple to set up your own view that took the data from your struct and computed the proper fractions, etc, hiding that complexity.
