### ISSUE TITLE
UserDefaults - working ?

### ISSUE THREAD

**Issue by pkasson** [stevengharris/SplitView#8]
Great component - tried to work direction with HSplitView ... not easy to go beyond basics.  

I have a UI with multiple tabs - 2 tabs are using Split but I want each to have them save their position to UserDefaults:

` 
let snippetFraction                 = FractionHolder.usingUserDefaults(Constants.Size.snippetFraction,  key: "snippetFraction")

let templateFraction                = FractionHolder.usingUserDefaults(Constants.Size.templateFraction, key: "templateFraction")
`

But, when switching tabs, the fraction value is still default - and wasn't sure if you could use your own keys.

Otherwise - thanks for this - saves lots of effort - great job !

**Comment by stevengharris** [comment]
Glad it's useful to you.

In your example, the `snippetFraction` and `templateFraction` should be retrieved from `UserDefaults.standard` based on the keys you supplied, so I'm not sure what's going on. If you want to use something other than `UserDefaults.standard`, you can use the more elaborate initializer for FractionHolder, like the `usingUserDefaults` function does:

```
public static func usingUserDefaults(_ fraction: CGFloat? = nil, key: String) -> FractionHolder {
    FractionHolder(
        fraction,
        getter: { UserDefaults.standard.value(forKey: key) as? CGFloat ?? fraction ?? 0.5 },
        setter: { fraction in UserDefaults.standard.set(fraction, forKey: key) }
    )
}
```

and just supply your own closures for `getter` and `setter`. In your case, if the `fraction` still comes up, not the new value that gets set as you drag, you could try debugging by putting a breakpoint or print statement in the `setter` and/or `getter` closure.

**Comment by pkasson** [comment]
I was not sure if you needed to use the keys you showed in the example ("myFraction").  So, I understand that it can't find something not stored in UserDefaults, how is the last state stored there ?

**Comment by stevengharris** [comment]
Yes, the idea is to use keys that make sense in the context of your app. For `fraction`, the Split view updates its CGFloat value whenever dragging stops, in `onEnded` using `fraction.value = privateFraction`:

```
    private func drag(in size: CGSize) -> some Gesture {
        return DragGesture()
            .onChanged { gesture in
                unhide(in: size)    // Unhide if the splitter is hidden, but resetting privateFraction first
                privateFraction = fraction(for: gesture, in: size)
                onDrag?(privateFraction)
                previousPosition = layout.isHorizontal ? privateFraction * size.width : privateFraction * size.height
            }
            .onEnded { gesture in
                previousPosition = nil
                fraction.value = privateFraction
            }
    }
```

**Comment by pkasson** [comment]
So with my code example, then your framework would have saved using my key "snippetFraction"  or is there a step I am missing ?

**Comment by stevengharris** [comment]
No, that's all there is to it.

**Comment by pkasson** [comment]
Yep - had to swap between 2 diff splitters in the .fraction() modifier - working now - thanks !
