### ISSUE TITLE
Set SplitView Constraints Maximum 

### ISSUE THREAD

**Issue by richardasmall** [stevengharris/SplitView#9]
Currently there only appears to be the ability to set a constraint to the minimum size. Being able to set the maximum would also be useful.

**Comment by stevengharris** [comment]
You can think of maxPFraction as being 1-minSFraction, and maxSFraction as being 1-minPFraction. IOW, limits on the max fraction of each side, primary and secondary, are already available by specifying the minimum fraction of the other side.
